### ISSUE TITLE
Crash on presumably iterative process involving boolean operator

### ISSUE THREAD

**Issue by martin-henz** [source-academy/js-slang#84]
function f(n){
	return n <= 0 ? true : (false || f(n - 1));
}
f(500);

**Comment by openorclose** [comment]
In the Source specs, `||` and `&&` needs both left and right operands to be booleans or else it will throw an error.

But during short circuit eval, it is said that `||` will always return the right side if the left side is false, which is how the above function can theoretically give rise to an iterative process as there are no deferred operations. 

This is untrue, as it is a check that the right hand side is a boolean value.

This problem exists not in the implementation of Source, but in the specifications itself. There is no way to guarantee that the right side of `||` will be a boolean, and thus `||` cannot short circuit.

**Comment by martin-henz** [comment]
Yes, we should fix the specification such that we say:

&&, ||: boolean x any -> any
and explicitly state that
e1 && e2 stands for: e1 ? e2 : false and
e1 || e2 stands for e1 ? true : e2.

**Comment by openorclose** [comment]
> function f(n){
> return n <= 0 ? true : (false || f(n - 1));
> }
> f(500);

So for Source 2018, should this still give rise to an iterative process? It seems that there are 2 schools of thought. 

Giving rise to an iterative process by doing short circuit evaluation

Giving rise to a recursive process when deferring the check-if-boolean operation as specified in the documentation.

**Comment by martin-henz** [comment]
I agree. We should not wait for 2019 to handle this. We should fix the specification to do proper short-circuiting, which makes the type check untenable.

**Comment by martin-henz** [comment]
Specs are updated.

**Comment by openorclose** [comment]
Disagree about good first issue.

Making || and && short circuit is be trivial enough by removing the type check.

https://github.com/source-academy/js-slang/blob/584f7c1519b18545c52e3648b9923896113df4a4/src/interpreter.ts#L484

Currently the interpreter only does naive proper tail calls, so merely short circuiting || && does not fix this issue. See ?:, which already short circuits, but does not result in an iterative process: [playground link](https://sourceacademy.nus.edu.sg/playground#chap=4&ext=NONE&prgrm=GYVwdgxgLglg9mABGOUCSUCmAnAhrAN0wAowBKRAbwChE7FtMoRskkBeTxABkQH4eiAFzJUGHPhhFSiALSIAjGQDc1AL7UU6LHkIkF3QyqA)

**Comment by thomastanck** [comment]
Resolved by #144.
